### PR TITLE
Adds initial Documentation

### PR DESCRIPTION
**Pull request by darigovresearch**
Following #37 an initial MVP built using readthedocs has been generated

### CODE REVIEW

**Comment by drspangle** [comment]
Something seems weird here. There's a bunch of binary files and output from the build process for the documentation added to the repo. Was this supposed to be tracked in version control, or is this just stuff you want/need to reference in the associated github pages?

**Comment by darigovresearch** [comment]
This is the first time we're building some readthedocs/sphynx documentation so can't say what's important and what isn't. Have removed the doctree folder files and  added it to a .gitignore. Would assume everything else is important unless someone from the community knows any better

**Comment by darigovresearch** [comment]
Is there anything else that is required for this pull request to be merged?

**Comment by drspangle** [comment]
I need to set up the github page for this. I'll try to get to this as soon as I can.

**Comment by darigovresearch** [comment]
No worries, happy to take a look at it if given access to the repo if that helps

**Comment by drspangle** [comment]
Can you clarify what level of access is required to set up a github page for this? Sorry, this hasn't been at the top of my agenda for a little while. I'm happy to engage with you to ensure that your contribution to the documentation is made useful.

**Comment by darigovresearch** [comment]
No worries at all for this not being the top of your agenda. The level required is the one that enables the "Settings tab in GitHub" (it may be the highest level possible).

However if you are unwilling to give that level of access all you need to do to enable docs the steps are as follows
1. Merge the pull request
2. Open the settings tab on GitHub
3. Go to the "Pages" tab on the left hand side of the page
4. Enable GitHub Pages
5. Set the source to be main/docs

It should then tell you the URL of the page which is based on the domain of the project. For example I have set this up on the fork which resulted in the following page

https://darigovresearch.github.io/infidel-sensor/build/html/

Also if you are busy happy to help reduce the workload for this repo by being an additional maintainer if you're not comfortable with full access at this point

**Comment by drspangle** [comment]
As far as merging the PR goes, I'm curious if it's necessary to include the files inside the `/build/html/_sources/` folder since it seems they're generated based on the .rst files and are build artifacts. Can you confirm?

**Comment by darigovresearch** [comment]
Believe the files in _sources are generated in order for the "Page source" functionality to work at the bottom of each page when the read the docs is rendered so removing them would break this feature.

This would suggest that they are necessary even if it is a duplicate
image

**Comment by darigovresearch** [comment]
@drspangle is there anything else that is required for this pull request to be merged?

**Comment by darigovresearch** [comment]
@drspangle thanks for merging and for adding me as a collaborator to the repository however I can't see the settings tab to enable the GitHub pages for you. Am afraid this may not be assignable to a collaborator in GitHub

image

You may need to follow the instructions in https://github.com/drspangle/infidel-sensor/pull/38#issuecomment-850858299 to enable it which I believe should then be at the following URL - https://drspangle.github.io/infidel-sensor/build/html/

I have added you as a collaborator to my fork to see if there is a way to enable you to see the settings tab on my repository.

**Pull request merged**
