### PR TITLE
fix capacitor grounds not connected

### LINKED ISSUE #27: Capacitor grounds not connected
As can be seen in the screenshots below, the grounds of the two capacitors are connected to each other and a ground fill island on the bottom side.
This ground fill island is then not connected to the rest of ground, but it should be.
Top side:
image
Bottom side:
image

### PR DESCRIPTION
**Pull request by eltobu**
Fixes #27 in KiCAD only

### CODE REVIEW

**Comment by eltobu** [comment]
Screenshots of fix, as requested
image
image

**Comment by drspangle** [comment]
It would be great if someone could also update the board layout in EAGLE  as well. Having two separate formats for the schematics and board layouts is going to be an ongoing problem unless each PR updates both formats, or we eliminate one of them.

**Comment by blurfl** [comment]
I'm willing to do the EAGLE change. Would you like it as a separate PR?

**Comment by drspangle** [comment]
@blurfl Fantastic! Let's include them both in the one PR to keep things organized.

**Comment by blurfl** [comment]
@drspangle, submitting changes to someone else's PR is new to me, not sure of the proper approach.
@eltobu, would you like to take care of the EAGLE changes, or should I submit a PR to your fork? Is there a third way?

**Comment by drspangle** [comment]
@blurfl You should be able to pull the branch associated with this PR and make commits to it. If that doesn't work, you can create a branch of that branch and then make commits to that, and create a new PR. Hopefully you won't end up having to do the latter.

**Comment by blurfl** [comment]
The branch associated with this PR is off the fork created by @eltobu, so I would need to fork his fork and submit a PR to his fork, he would need to approve my PR on his fork, and that would percolate up to be reflected in his PR #28 here. If there is a better way, I'm glad to learn.

Could I please submit a separate PR for the EAGLE changes here directly instead? I probably should regenerate the Gerber files as well as changing the PCB file. If yes, would you want to specify the PR title?
 Here's the proposed change to the EAGLE pcb:
infidel-pcb-EAGLE-SMD-fix

**Comment by drspangle** [comment]
@blurfl Oh, I see. Better create a separate PR then. I really thought that it would have created a mirrored branch automatically but I guess since this is a fork that's not how it works anymore, they're only connected by the shared history and not the actual branch. I'll merge this one in, but I'll leave the issue #27 open.

**Comment by drspangle** [comment]
@blurfl Now that this has been merged into the main branch, just update your branch and you should be fine to submit your PR. You can call it whatever you like, I'll know it's connected with the original issue.

**Pull request merged**
