### PR TITLE
Update Lever.stl

### PR DESCRIPTION
**Pull request by darraghbr**
Update Lever.stl to remove infinitely thin walls and generally improve printability

Addresses issue #9

### CODE REVIEW

**Comment by darraghbr** [comment]
You can see the original file on the left and my updated version on the right.

image

**Comment by darraghbr** [comment]
The new CPL and BOM address issue #10 but beware you will need to procure and solder on a switch seperately.

**Comment by blurfl** [comment]
I wonder whether you can include the updated 'LeverPlastic' body from the f3z file? Not the whole f3z, just the changed lever body.

**Comment by blurfl** [comment]
Why remove the switch instead of correcting the placement? 
FWIW, I had a set of boards made at JLCPCB from the original BOM, their automation corrected the part placement issues properly.

**Comment by drspangle** [comment]
@darraghbr These are nice changes. For to sake of keeping things easier to track in the revision history, could I ask you very kindly to submit a separate PR for each of these issues? That is to say, a separate PR addressing #9 and then a separate one for #11. Thank you! I will close this PR once the separate ones are up.

**Comment by darraghbr** [comment]
> 
> 
> Why remove the switch instead of correcting the placement?
> FWIW, I had a set of boards made at JLCPCB from the original BOM, their automation corrected the part placement issues properly.

That was the first thing I tried, but I can't get it to work, I've tried moving all the components 1.27mm to the right, to no avail and I've tried just moving the switch 1.27mm to the right, which gets the switch in the right place but doesn't work for the rest of the changes. The only thing I've managed to get working is to remove the switch.

JLC will accept it, but they will have to manually go and change the positions for you.

**Comment by drspangle** [comment]
@darraghbr Let me know when this is ready for review. It should only take a moment.

**Comment by darraghbr** [comment]
> 
> 
> @darraghbr Let me know when this is ready for review. It should only take a moment.

Go for it buddy, one of my associates at 3DCrowd looked over it so can ask him to weigh in as well @Judoguy12

**Comment by drspangle** [comment]
@darraghbr I'm wondering if there's a git-lfs issue here, as the STL seems to be empty. Would you mind including the source files? Ideally we should try to keep them in a plaintext format if possible.

**Comment by drspangle** [comment]
@Judoguy12 I would very much appreciate your input on this as well.

**Comment by darraghbr** [comment]
> 
> 
> Would you mind including the source files? Ideally we should try to keep them in a plaintext format if possible.

I'm afraid because everything is all designed within one file it's challenging to make changes that don't break other things, for instance when I make this change, the text on the outside of the main housing breaks and for some reason becomes a different size. I have printed the new lever in tandem with the original housing and it still fits fine.

**Comment by drspangle** [comment]
> 
> 
> > Would you mind including the source files? Ideally we should try to keep them in a plaintext format if possible.
> 
> I'm afraid because everything is all designed within one file it's challenging to make changes that don't break other things, for instance when I make this change, the text on the outside of the main housing breaks and for some reason becomes a different size. I have printed the new lever in tandem with the original housing and it still fits fine.

That's a pity. Thanks anyway. Let's have a few others chime in with their printing results and I'll set about merging this. I will also need a week before I'm able to get access to my printing facilities again too, but I'd like to test this out for myself.

**Comment by blurfl** [comment]
In the Fusion file, right-click on the LeverNew:1 component to see the 'Export...' option for that part. That will create an .f3d file of just this part.

**Comment by blurfl** [comment]
In the original, the cavities for the two 10mm bearings affected by this change are modeled at exactly 10mm diameter. How about increasing that by 0.1mm-0.2mm to make it easier to press those bearings in?

**Comment by drspangle** [comment]
I still haven't had a chance yet to print these pieces and test this PR, but this hasn't dropped off my radar.

**Comment by blurfl** [comment]
Interested to hear what orientation and settings work best for you on this part.

**Comment by Judoguy12** [comment]
I'll be printing this tonight and I'll post a profile if it works

**Comment by Judoguy12** [comment]
Sorry that took a bit longer than expected - printer fun - the lever looks good printed with 0.2mm layer heights in PLA I'll post my config bundle later for my Artillery Genius
PXL_20210318_161656867 MP
PXL_20210318_161653004 MP
PXL_20210318_161649193 MP

**Comment by drspangle** [comment]
@deezums has raised some problems with this change in the discussion thread for #9. I'm concerned that these printability changes may prove to be less ideal for the overall mechanical design. They specifically raise the issue that what has been changed here may have been an intentional design feature. Can anyone remark on this further?

**Comment by darraghbr** [comment]
> 
> 
> @deezums has raised some problems with this change in the discussion thread for #9. I'm concerned that these printability changes may prove to be less ideal for the overall mechanical design. They specifically raise the issue that what has been changed here may have been an intentional design feature. Can anyone remark on this further?

Absolutely not, none of the principle features have been moved or altered in any way, all I have done is thickened up some of the walls (because some of them were infinitely thin) and reduced some of the chamfers.

**Comment by drspangle** [comment]
From what I can tell, this has improved from the original so I will include it. We can always roll back if people are running into problems.

**Pull request merged**
