### PR TITLE
Update CPL and BOM

### PR DESCRIPTION
**Pull request by darraghbr**
The new CPL and BOM addresses issue #11  but beware you will need to procure and solder on a switch seperately.

image

### CODE REVIEW

**Comment by drspangle** [comment]
@blurfl Do you have any remarks about this change?

@darraghbr I will take a close look at this change and review it before it's accepted into the main branch. Can you provide a bit more detail about precisely the problem this addresses? I noticed some discussion in the previous PR, perhaps you can elaborate here.

**Comment by darraghbr** [comment]
There was some previous discussion in PR #10 

I discovered that there is some sort of issue with the original CPL file, all of the components are shifted 1.27 mm to the left as referenced in #11 the only way I have been able to fix this is by removing the switch from the BOM and CPL file. Obviously this is not ideal.

I'm not entirely convinced you should throw this onto main, as ultimately JLC (and presumably any other board house) will just accept the files as they are and fix it for you, but it could serve as an intermediary fix while a better fix is come up with. (I am going to email JLC shortly to see if it's something on their end)

**Comment by drspangle** [comment]
@darraghbr Thanks, this is still an important contribution. I'll of course leave this PR open and once a final determination is made we can either modify this PR accordingly or go in another direction.

**Comment by blurfl** [comment]
About the BOM changes - let's find a fix that doesn't leave the switch unmounted. The problem may be internal to JLCPCB, as there was a comment to that effect when I had a run of these boards made that flagged these placement issues. They were able to properly build the board with no intervention on my part. The coordinates listed for SW1 are correct in the original BOM file.

**Comment by darraghbr** [comment]
Yes that's fair, I will close this PR, I will leave the issue open.

**Pull request closed without merging**
